; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "TestFileUtils"
#define MyAppVersion "1.0"
#define MyAppPublisher "Tee"
#define MyAppExeName "MyProg.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{647DACF2-B578-4B35-89D5-701B360A9F90}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
CreateAppDir=no
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputDir=.\
OutputBaseFilename=TestFileUtilsSetup
Compression=lzma2/ultra64
LZMAUseSeparateProcess=yes
LZMADictionarySize=327680
LZMANumBlockThreads=1
LZMANumFastBytes=224
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Code]
#include "..\SystemtimeUtils.iss"
#include "..\FileUtils.iss"
#include "UnitTestFileUtils.iss"

// [Files]
// Source: "C:\git_st\Delphi\InnoSetupFB4\HelperBin\HashInfo.txt"; DestDir: "{win}"; Flags: ignoreversion
//  NOTE: Don't use "Flags: ignoreversion" on any shared system files

